# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 362c33e01ffadb734430c9e8ec0bb9961532fc3c137d7c9caed218ecb8212c4bc3e1833055034b0a5c7a9bba175a9c474c26f665250344b94762e2806fc2c598

test:
  secret_key_base: a16846632b1a6f92c67f5a47f5f62d74a37dce6e6975fc4c8941070b5b0db3334fb0975d5eb0cdfc96fae751f8fe06bb97f32faa7093916a0d87250dee937c0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
